### ISSUE TITLE
Not able to upload large files using mongrel

### ISSUE THREAD

**Issue by AntonTrapp** [evan/mongrel#3] opened 2010-04-12 04:50 UTC
Sun Apr 11 06:13:21 +0000 2010: Error reading HTTP body: #<RuntimeError: Socket read returned insufficient data: 3374>
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel/http_request.rb:107:in `read_socket'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel/http_request.rb:86:in`read_body'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel/http_request.rb:55:in `initialize'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel.rb:149:in`new'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel.rb:149:in `process_client'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel.rb:285:in`run'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel.rb:285:in `initialize'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel.rb:285:in`new'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel.rb:285:in `run'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel.rb:268:in`initialize'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel.rb:268:in `new'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel.rb:268:in`run'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel/configurator.rb:282:in `run'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel/configurator.rb:281:in`each'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel/configurator.rb:281:in `run'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/mongrel_rails:128:in`run'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/../lib/mongrel/command.rb:212:in `run'
/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/bin/mongrel_rails:281
/usr/bin/mongrel_rails:19:in`load'
/usr/bin/mongrel_rails:19

(Simple multipart with a zip or text file of some hundret mb)

**Comment by luislavena** [comment] 2010-04-14 13:11
How the big file has been uploaded? Using a flash based upload?

Please provide more information about the request headers that might indicate Content-Length or similar.

Thank you.

**Comment by AntonTrapp** [comment] 2010-04-15 08:48
Tried it with ZIP files and plain ASCII files. Example: http://hydrogis.broler.eu/samples/Mash.zip (happens with the zip and with the unpacked text file on remote servers (does not happen local!).
Couldn't find a way around it, so I changed to passenger after years of mungrel happiness... - so I can't tell you much more to this topic if you can not reproduce the error. System was Debian Lenny with apache 2 (newest security patches) and the current mongrel / mongrel_cluster.

**Comment by luislavena** [comment] 2010-04-15 11:43
So,

If you used mongrel locally during development and tried to upload big files, and didn't fail means the issue is somewhere else and not mongrel itself.

Depends on how you configured Apache to proxy to your mongrel cluster.

Since you no longer have it in production to provide more details, will close this out.

Feel free to reopen the issue once you can reproduce locally.

**Closed as completed by luislavena** 2010-04-15 11:43 UTC
Labels: feedback

**Comment by amittomer25** [comment] 2010-10-07 12:51
but i uploaded 7 GB of file sucessfully running mongrel alone and mongrel+apache
